import 'dart:ui';

/// Generated by AssetsRefGenerator on 2021/06/27
class Res {
  static const String logo_game_tv = "assets/logo_game_tv.png";
  static const String user_9876543210 = "assets/user_9876543210.jpg";
  static const String user_9898989898 = "assets/user_9898989898.jpg";
}


class Keys{
  static const String IS_LOGIN = "is_login";
  static const String MachineID = "machine_id";
  static const String USER = "username";
}

class AppFonts {
  static const String app_font_family = "Poppins";
}

class AppFontWeight
{
  static const FontWeight BOLD = FontWeight.w700;
  static const FontWeight LIGHT = FontWeight.w300;
  static const FontWeight SEMI_BOLD = FontWeight.w600;
  static const FontWeight MEDIUM = FontWeight.w500;
  static const FontWeight REGULAR = FontWeight.w400;
  static const FontWeight THIN = FontWeight.w100;
  static const FontWeight BLACK = FontWeight.w900;
}

class AppDimension
{
  static const double size20 = 20.0;
  static const double size18 = 18.0;
  static const double size12 = 12.0;
  static const double size13 = 13.0;
  static const double size10 = 10.0;
  static const double size14 = 14.0;
  static const double size16 = 16.0;
  static const double size24 = 24.0;
}

class AppColors{
  static const Color primary_color = Color(0xFFFF8C00);
  static const Color primary_color_light = Color(0xFFFFC800);
  static const Color color_white = Color(0xFFFFFFFF);
  static const Color color_black_text= Color(0xFF555964);
  static const Color color_grey_text= Color(0xFF969292);
  static const Color color_green= Color(0xFF166d20);
  static const Color color_red= Color(0xFFdd3009);
  static const Color color_red_light= Color(0xfffd8158);
  static const Color color_grey_bg = Color(0xFFF8F9FB);
  static const Color color_light_blue_border = Color(0xFF49CCE0);
  static const Color blue_dark = Color(0xFF00587C);
  static const Color purple_dark = Color(0xFF6C3483);
  static const Color purple_light = Color(0xFFAF7AC5);
}

class PageRoutes {
  // static const String home = homePage.routeName;


}

// class AppData{
//   Map<String,String> loginData = Map();
//   AppData(){
//     loginData['9898989898'] = 'password12';
//     loginData['9876543210'] = 'password12';
//   }
// }
